 export const plans = [
  {
    name: "Mensal",
    price: "US$ 9,99",
    period: "/mês",
    savings: null,
    highlighted: false,
    features: [
      { text: "3 dispositivos simultâneos", included: true },
      { text: "62 países disponíveis", included: true },
      { text: "Criptografia AES-256", included: true },
      { text: "Política zero-log", included: true },
      { text: "Suporte por e-mail", included: true },
      { text: "Servidores dedicados", included: false },
      { text: "Suporte prioritário 24/7", included: false },
    ],
  },
  {
    name: "Anual",
    price: "US$ 4,99",
    period: "/mês",
    savings: "Economize 50% — US$ 59,88/ano",
    highlighted: true,
    features: [
      { text: "10 dispositivos simultâneos", included: true },
      { text: "62 países disponíveis", included: true },
      { text: "Criptografia AES-256", included: true },
      { text: "Política zero-log", included: true },
      { text: "Suporte prioritário 24/7", included: true },
      { text: "Servidores dedicados", included: true },
      { text: "Acesso antecipado a novidades", included: false },
    ],
  },
  {
    name: "Bienal",
    price: "US$ 2,99",
    period: "/mês",
    savings: "Economize 70% — melhor custo total",
    highlighted: false,
    features: [
      { text: "10 dispositivos simultâneos", included: true },
      { text: "62 países disponíveis", included: true },
      { text: "Criptografia AES-256", included: true },
      { text: "Política zero-log", included: true },
      { text: "Suporte prioritário 24/7", included: true },
      { text: "Servidores dedicados", included: true },
      { text: "Acesso antecipado a novidades", included: true },
    ],
  },
];